/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestCanvas */

#ifndef _Included_TestCanvas
#define _Included_TestCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef TestCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define TestCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef TestCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define TestCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef TestCanvas_FOCUS_TRAVERSABLE_SET
#define TestCanvas_FOCUS_TRAVERSABLE_SET 2L
#undef TestCanvas_TOP_ALIGNMENT
#define TestCanvas_TOP_ALIGNMENT 0.0f
#undef TestCanvas_CENTER_ALIGNMENT
#define TestCanvas_CENTER_ALIGNMENT 0.5f
#undef TestCanvas_BOTTOM_ALIGNMENT
#define TestCanvas_BOTTOM_ALIGNMENT 1.0f
#undef TestCanvas_LEFT_ALIGNMENT
#define TestCanvas_LEFT_ALIGNMENT 0.0f
#undef TestCanvas_RIGHT_ALIGNMENT
#define TestCanvas_RIGHT_ALIGNMENT 1.0f
#undef TestCanvas_serialVersionUID
#define TestCanvas_serialVersionUID -7644114512714619750LL
#undef TestCanvas_serialVersionUID
#define TestCanvas_serialVersionUID -2284879212465893870LL
/*
 * Class:     TestCanvas
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_TestCanvas_paint
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
