
INC = -I . -I numeric -I presentation -I datamodel -I control -I presentation/commands
SRC = main.cc numeric/*.cc presentation/*.cc datamodel/*.cc control/*.cc presentation/commands/*.cc


one:
	g++ $(INC) -o rpn $(SRC)


clean: 
	@rm -f rpn
